apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test-app-fe
  namespace: integration-test-app
  labels:
    app: web
    app.armada.ai/role: frontend
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  selector:
    matchLabels:
      app: web
      app.armada.ai/role: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        app.armada.ai/role: frontend
        app.armada.ai/type: marketplace-apps
    spec:
      containers:
        - name: nginx
          image: nginx
          securityContext:
            allowPrivilegeEscalation: false
            # runAsNonRoot: true
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: integration-test-app-fe
  namespace: integration-test-app
  # ownerReferences:
  # - apiVersion: apps/v1
  #   kind: Deployment
  #   name: integration-test-app-fe
    # uid: 44821640-b484-45b4-85a8-5b12e2985cf8
  labels:
    app.armada.ai/role: frontend
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  type: NodePort
  selector:
    app: web
    tier: front-end
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test-app-be
  namespace: integration-test-app
  labels:
    app: web
    app.armada.ai/role: backend
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  selector:
    matchLabels:
      app: web
      app.armada.ai/role: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        app.armada.ai/role: backend
        app.armada.ai/type: marketplace-apps
    spec:
      containers:
        - name: nginx
          image: nginx
          securityContext:
            allowPrivilegeEscalation: false
            # runAsNonRoot: true
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: integration-test-app-be
  namespace: integration-test-app
  # ownerReferences:
  # - apiVersion: apps/v1
  #   kind: Deployment
  #   name: integration-test-app-be
  #   uid: 6d650deb-1444-431c-870b-bd8adef51d6a
  labels:
    app.armada.ai/role: backend
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  type: NodePort
  selector:
    app: web
    app.armada.ai/role: backend
  ports:
    - port: 80
      targetPort: 80
