apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test-app-fe
  namespace: metrics-test-app
  labels:
    app: web
    app.armada.ai/role: frontend
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  selector:
    matchLabels:
      app: web
      app.armada.ai/role: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        app.armada.ai/role: frontend
        app.armada.ai/type: marketplace-apps
    spec:
      containers:
        - name: go-app
          image: justinjosephqb/go-app:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
