apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: stateful-set
  labels:
     app.kubernetes.io/instance: 3e673979-56ff-4172-93e3-f22503a5e855
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
