apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: stateful-set
  labels:
    app: web
    app.armada.ai/role: stateful-set
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: stateful-test-app
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
