apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-test-app-be
  namespace: metrics-test-app
  labels:
    app: web
    app.armada.ai/role: frontend
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  selector:
    matchLabels:
      app: web
      app.armada.ai/role: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        app.armada.ai/role: frontend
        app.armada.ai/type: marketplace-apps
    spec:
      containers:
        - name: metrics-test-app-be
          image: justinjosephqb/metrics-test-app-be:latest
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-test-app-be
spec:
  selector:
    app: metrics-test-app-be
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
