apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test-app
  labels:
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: "integration-test-app"
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        app.armada.ai/type: marketplace-apps
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: DoesNotExist
      containers:
        - name: nginx
          image: nginx
          securityContext:
            allowPrivilegeEscalation: false
            # runAsNonRoot: true
          ports:
            - containerPort: 80
--------
apiVersion: v1
kind: Service
metadata:
  name: integration-test-app-service
  labels:
    app.kubernetes.io/instance: "a17cdc20-378b-4c57-b16a-91f8cdcb3dc2"
    app.armada.ai/name: "integration-test-app"
    app.armada.ai/type: "armada"
spec:
  selector:
    app: integration-test-app
  ports:
    - port: 80
      targetPort: 80
            
