apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test-app-fe
  namespace: integration-test-app
  labels:
    app: web
    tier: front-end
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  selector:
    matchLabels:
      app: web
      tier: front-end
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        tier: front-end
        app.armada.ai/type: marketplace-apps
    spec:
      containers:
        - name: nginx
          image: nginx
          securityContext:
            allowPrivilegeEscalation: false
            # runAsNonRoot: true
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: integration-test-app-fe
  namespace: integration-test-app
  labels:
    tier: front-end
spec:
  type: NodePort
  selector:
    app: web
    tier: front-end
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test-app-be
  namespace: integration-test-app
  labels:
    app: web
    tier: backend
    app.armada.ai/type: marketplace-apps
    app.armada.ai/name: integration-test-app
spec:
  selector:
    matchLabels:
      app: web
      tier: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        tier: backend
        app.armada.ai/type: marketplace-apps
    spec:
      containers:
        - name: nginx
          image: nginx
          securityContext:
            allowPrivilegeEscalation: false
            # runAsNonRoot: true
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: integration-test-app-be
  namespace: integration-test-app
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: web
    tier: backend
  ports:
    - port: 80
      targetPort: 80
